"""
AgentMem OS — Database Models
==============================
Implements the full 4-tier memory hierarchy:

  Tier 1: Working Memory    → managed in Redis (not ORM)
  Tier 2: Episodic Memory   → Turn table
  Tier 3: Semantic Memory   → Summary + SemanticChunk tables
  Tier 4: Procedural Memory → ProceduralPattern table

Additional:
  - KnowledgeGraphNode / KnowledgeGraphEdge: Entity graph persistence
  - AgentNamespace: Multi-agent isolation
  - CostLog: API cost tracking
"""

from datetime import datetime
from sqlalchemy import (
    Column, String, Integer, Float, DateTime,
    ForeignKey, Text, Boolean, JSON
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


# ──────────────────────────────────────────────────────────────────────────────
# AGENT NAMESPACE  (multi-agent isolation — Phase 4)
# ──────────────────────────────────────────────────────────────────────────────

class AgentNamespace(Base):
    """
    Each agent gets its own namespace. Episodic memory is private per agent.
    Semantic memories can be promoted to a shared pool (shared_pool=True).
    """
    __tablename__ = "agent_namespaces"

    agent_id   = Column(String, primary_key=True)
    name       = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    metadata_  = Column(JSON, default=dict)     # arbitrary agent config

    sessions   = relationship("Session", back_populates="agent")


# ──────────────────────────────────────────────────────────────────────────────
# SESSION  (branching conversation tree)
# ──────────────────────────────────────────────────────────────────────────────

class Session(Base):
    """
    Root entity for a conversation thread. Supports parent-child branching.
    branch_type: 'root' | 'hard' (new direction) | 'soft' (minor variant)
    """
    __tablename__ = "sessions"

    session_id         = Column(String, primary_key=True)
    agent_id           = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=True)
    parent_session_id  = Column(String, ForeignKey("sessions.session_id"), nullable=True)
    branch_point_turn  = Column(Integer, nullable=True)
    inherited_context  = Column(Text, nullable=True)   # snapshot of parent at branch time
    name               = Column(String, nullable=True)
    model              = Column(String, nullable=True)
    branch_type        = Column(String, default="root")
    created_at         = Column(DateTime, default=datetime.utcnow)
    total_tokens       = Column(Integer, default=0)
    total_cost_usd     = Column(Float, default=0.0)
    is_archived        = Column(Boolean, default=False)

    # Relationships
    agent    = relationship("AgentNamespace", back_populates="sessions")
    parent   = relationship("Session", remote_side=[session_id], back_populates="children")
    children = relationship("Session", back_populates="parent")
    turns    = relationship("Turn", back_populates="session", cascade="all, delete-orphan")
    summaries= relationship("Summary", back_populates="session", cascade="all, delete-orphan")


# ──────────────────────────────────────────────────────────────────────────────
# TIER 2: EPISODIC MEMORY — raw conversation turns
# ──────────────────────────────────────────────────────────────────────────────

class Turn(Base):
    """
    A single message in a conversation (user or assistant).
    importance_score is computed by the MemoryImportanceScorer before compression.
    """
    __tablename__ = "turns"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    session_id       = Column(String, ForeignKey("sessions.session_id"))
    role             = Column(String, nullable=False)      # 'user' | 'assistant' | 'system'
    content          = Column(Text, nullable=False)
    token_count      = Column(Integer, default=0)
    created_at       = Column(DateTime, default=datetime.utcnow)

    # AgentMem OS additions
    importance_score = Column(Float, default=0.0)          # 0.0–1.0, set by MemoryImportanceScorer
    entity_count     = Column(Integer, default=0)          # NER entity count, set at save time
    semantic_novelty = Column(Float, default=0.0)          # distance from existing summaries
    is_compressed    = Column(Boolean, default=False)       # True once included in a Summary

    session = relationship("Session", back_populates="turns")


# ──────────────────────────────────────────────────────────────────────────────
# TIER 3: SEMANTIC MEMORY — compressed, meaning-indexed
# ──────────────────────────────────────────────────────────────────────────────

class Summary(Base):
    """
    A compressed semantic summary of one or more turns.
    Generated by the SleepConsolidationEngine.
    Also indexed in ChromaDB for semantic retrieval.
    """
    __tablename__ = "summaries"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    session_id      = Column(String, ForeignKey("sessions.session_id"))
    agent_id        = Column(String, nullable=True)        # set for shared-pool promotions
    turn_range      = Column(String, nullable=False)       # e.g. "42-67"
    content         = Column(Text, nullable=False)
    entities        = Column(Text, nullable=True)          # comma-separated entity names
    cluster_id      = Column(Integer, nullable=True)       # DBSCAN cluster this belongs to
    abstraction_level = Column(Integer, default=1)         # 1=episode, 2=pattern, 3=principle
    is_shared       = Column(Boolean, default=False)       # promoted to multi-agent shared pool
    created_at      = Column(DateTime, default=datetime.utcnow)

    session = relationship("Session", back_populates="summaries")


# ──────────────────────────────────────────────────────────────────────────────
# TIER 4: PROCEDURAL MEMORY — learned patterns and behavioral templates
# ──────────────────────────────────────────────────────────────────────────────

class ProceduralPattern(Base):
    """
    A reusable behavioral pattern or skill extracted from episodic sequences.
    Example: "When user reports a bug → ask for minimal reproduction first"

    Extracted by: PatternExtractor (Phase 3D)
    Used by: ContextAssembler to inject relevant procedural context
    """
    __tablename__ = "procedural_patterns"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    agent_id        = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=True)
    trigger         = Column(Text, nullable=False)         # "When X..."
    action          = Column(Text, nullable=False)         # "...do Y"
    full_pattern    = Column(Text, nullable=False)         # human-readable if-then
    confidence      = Column(Float, default=0.5)          # 0.0–1.0
    support_count   = Column(Integer, default=1)           # how many episodes support this
    source_sessions = Column(Text, nullable=True)          # comma-sep session IDs
    embedding_id    = Column(String, nullable=True)        # ChromaDB doc ID
    created_at      = Column(DateTime, default=datetime.utcnow)
    last_used_at    = Column(DateTime, nullable=True)
    is_global       = Column(Boolean, default=False)       # shared across all agents


# ──────────────────────────────────────────────────────────────────────────────
# ENTITY KNOWLEDGE GRAPH — the Global Map (fills the 10% context slot)
# ──────────────────────────────────────────────────────────────────────────────

class KnowledgeGraphNode(Base):
    """
    A named entity extracted from conversation turns via spaCy NER.
    Node in the persistent Entity Knowledge Graph.
    """
    __tablename__ = "kg_nodes"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    agent_id    = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=True)
    session_id  = Column(String, nullable=True)            # originating session
    entity_text = Column(String, nullable=False)           # "Python", "OpenAI", "Sahith"
    entity_type = Column(String, nullable=False)           # spaCy label: ORG, PERSON, TECH, etc.
    mention_count = Column(Integer, default=1)
    first_seen  = Column(DateTime, default=datetime.utcnow)
    last_seen   = Column(DateTime, default=datetime.utcnow)


class KnowledgeGraphEdge(Base):
    """
    A co-occurrence relationship between two entities.
    Weight increases every time both appear in the same turn.
    """
    __tablename__ = "kg_edges"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    source_id   = Column(Integer, ForeignKey("kg_nodes.id"), nullable=False)
    target_id   = Column(Integer, ForeignKey("kg_nodes.id"), nullable=False)
    weight      = Column(Float, default=1.0)               # co-occurrence count
    session_id  = Column(String, nullable=True)
    last_updated = Column(DateTime, default=datetime.utcnow)


# ──────────────────────────────────────────────────────────────────────────────
# COST LOG — API cost tracking per call
# ──────────────────────────────────────────────────────────────────────────────

class CostLog(Base):
    """Tracks API cost per LLM call with cached token savings."""
    __tablename__ = "cost_log"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    session_id     = Column(String, ForeignKey("sessions.session_id"))
    agent_id       = Column(String, nullable=True)
    model          = Column(String, nullable=False)
    input_tokens   = Column(Integer, default=0)
    output_tokens  = Column(Integer, default=0)
    cached_tokens  = Column(Integer, default=0)
    cost_usd       = Column(Float, default=0.0)
    timestamp      = Column(DateTime, default=datetime.utcnow)


# ──────────────────────────────────────────────────────────────────────────────
# CONSOLIDATION LOG — track Sleep Consolidation Engine runs
# ──────────────────────────────────────────────────────────────────────────────

class ConsolidationLog(Base):
    """
    Audit trail for every Sleep Consolidation Engine run.
    Useful for benchmarking and the research paper evaluation section.
    """
    __tablename__ = "consolidation_log"

    id                  = Column(Integer, primary_key=True, autoincrement=True)
    session_id          = Column(String, nullable=True)
    turns_processed     = Column(Integer, default=0)
    clusters_found      = Column(Integer, default=0)
    summaries_generated = Column(Integer, default=0)
    tokens_before       = Column(Integer, default=0)
    tokens_after        = Column(Integer, default=0)
    compression_ratio   = Column(Float, default=0.0)       # tokens_after / tokens_before
    duration_seconds    = Column(Float, default=0.0)
    triggered_by        = Column(String, default="scheduled")  # 'scheduled' | 'threshold' | 'manual'
    timestamp           = Column(DateTime, default=datetime.utcnow)


# ──────────────────────────────────────────────────────────────────────────────
# PHASE 4: MEMORY FEDERATION PROTOCOL
# ──────────────────────────────────────────────────────────────────────────────

class AgentTrustScore(Base):
    """
    Pairwise trust scores between agents in the federation.

    Trust is directional: agent_from trusts agent_to with score ∈ [0, 1].
    When agent_from retrieves memories from agent_to and those memories
    prove useful (positive feedback), trust increases. Negative feedback
    or disuse causes slow decay.

    Trust update rule (exponential moving average):
        trust_new = α × trust_old + (1 − α) × feedback_signal
        α = 0.8  (trust earned slowly, lost slowly)

    Initialized to 0.5 (neutral) for all new pairs.
    Fork relationships start at 0.9 (child trusts parent by default).
    """
    __tablename__ = "agent_trust_scores"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    agent_from     = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=False)
    agent_to       = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=False)
    trust_score    = Column(Float, default=0.5)            # 0.0 = untrusted, 1.0 = fully trusted
    interaction_count = Column(Integer, default=0)         # total interactions that shaped this score
    last_updated   = Column(DateTime, default=datetime.utcnow)
    created_at     = Column(DateTime, default=datetime.utcnow)


class FederatedMemoryEntry(Base):
    """
    A memory promoted to the cross-agent shared pool by the MFP (Memory Federation Protocol).

    Only memories with abstraction_level >= 2 (pattern or principle) are eligible.
    Raw episodic turns NEVER enter the federated pool — this is a privacy guarantee.

    Fields:
      source_agent_id   — which agent produced this memory
      content           — the abstracted summary text
      abstraction_level — 2 (pattern) or 3 (principle)
      promotion_score   — the score that triggered promotion
      access_count      — how many agents have retrieved this entry
      last_accessed_at  — used for relevance aging / decay
      chroma_doc_id     — pointer to ChromaDB for vector retrieval
    """
    __tablename__ = "federated_memory"

    id                = Column(Integer, primary_key=True, autoincrement=True)
    source_agent_id   = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=False)
    source_session_id = Column(String, nullable=True)
    content           = Column(Text, nullable=False)
    abstraction_level = Column(Integer, default=2)         # 2=pattern, 3=principle
    promotion_score   = Column(Float, default=0.0)         # score that qualified this entry
    access_count      = Column(Integer, default=0)         # times retrieved by other agents
    last_accessed_at  = Column(DateTime, nullable=True)
    chroma_doc_id     = Column(String, nullable=True)      # ChromaDB document ID
    is_active         = Column(Boolean, default=True)      # False = decayed/retired
    created_at        = Column(DateTime, default=datetime.utcnow)


class AgentForkRecord(Base):
    """
    Records the parent-child relationship when an agent is forked.

    Forking means: new_agent inherits all L2/L3 summaries from parent_agent
    as its initial semantic knowledge base, but builds its own episodic layer
    from scratch. Analogous to git branch from a commit.

    The fork_depth tracks inheritance chains:
      parent (depth=0) → child (depth=1) → grandchild (depth=2)
    """
    __tablename__ = "agent_fork_records"

    id              = Column(Integer, primary_key=True, autoincrement=True)
    parent_agent_id = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=False)
    child_agent_id  = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=False)
    fork_depth      = Column(Integer, default=1)           # 1=direct child, 2=grandchild, etc.
    summaries_inherited = Column(Integer, default=0)       # how many summaries were copied
    patterns_inherited  = Column(Integer, default=0)       # how many patterns were copied
    forked_at       = Column(DateTime, default=datetime.utcnow)


class MemoryAccessLog(Base):
    """
    Log of every time an agent retrieves a FederatedMemoryEntry.
    Used for:
      - Decay: entries never accessed by other agents are eventually retired.
      - Trust updates: positive feedback from this agent about source_agent.
      - Analytics: which memories are most valuable across the federation.
    """
    __tablename__ = "memory_access_log"

    id                    = Column(Integer, primary_key=True, autoincrement=True)
    accessing_agent_id    = Column(String, ForeignKey("agent_namespaces.agent_id"), nullable=False)
    federated_entry_id    = Column(Integer, ForeignKey("federated_memory.id"), nullable=False)
    query_text            = Column(Text, nullable=True)    # what the agent was querying
    relevance_score       = Column(Float, default=0.0)     # cosine similarity at retrieval time
    feedback_signal       = Column(Float, nullable=True)   # 0.0–1.0, set after interaction
    accessed_at           = Column(DateTime, default=datetime.utcnow)
